# https://docs.gitlab.com/charts/charts/globals#configure-postgresql-settings
# https://docs.gitlab.com/ee/administration/database_load_balancing.html
global:
  psql:
    load_balancing:
      # #service-discovery
      discover:
        nameserver: some.consul
        record: secondary.postgresql.service.consul
        record_type: A
        port: 8600
        interval: 60
        disconnect_timeout: 120
postgresql:
  install: false